version: '3.9'
services:
  # Сервис для разворачивания контейнера с базой данных
  postgres:
    container_name: postgres
    image: postgres:12
    hostname: database
    volumes:
      - db_data:/var/lib/postgres
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=wallet
    networks:
      - wallet-network
    ports:
      - "5430:5432"
  # Сервис для разворачивания контейнера с приложением
  webapi:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - wallet-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/wallet
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=wallet
    healthcheck:
      test: curl http://webapi:8080 || exit 0
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s

networks:
  wallet-network:
    driver: bridge

volumes:
  db_data: