spring:
  application:
    name: PassTracker
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wallet}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dbchangelog.xml
  data:
    redis:
      host: redis
      port: 6380
      username: redis_user
      password: redis_pass

jwt:
  signing-key: "my-super-long-secret-key-that-can-secure-your-account-data"
  expiration-time: 1000000000

